React router update
learn-co-curriculum/react-hooks-react-router-routes-lab pull request #5
Opened 2023-07-20 19:22 UTC by Matt-Eva

2023-07-28 20:51 UTC, lizbur10 requested changes
This is looking good. A few things:

1. It doesn't really make sense to me that a list of MovieCard components is rendered on the Home page and then students are asked to add code to render the same info on the Movie page. I suggest just having students render a list of movie titles on the home page and then use the UserCard on the Movie page
2. It might be a good idea to mention that translating titles into routes (and back) will be handled automatically so students don't need to worry about it.
3. When I run the tests I'm getting an error about "/bad-route" not being found (in the test of the error page). The tests are all passing but it would probably be good if we can find a way suppress or clear that error.
4. The tests are also throwing warnings about using the regex global modifier. I just removed them from my test files and it worked fine so I'll do that here as well.

2023-07-28 21:32 UTC, lizbur10 reviewed
Removing global flag from test files

2023-07-28 21:32 UTC, lizbur10 commented on src/__tests__/Actors.test.js
>    const h1 = screen.queryByText(/Actors Page/g);
```suggestion
  const h1 = screen.queryByText(/Actors Page/);
```

2023-07-28 21:32 UTC, lizbur10 commented on src/__tests__/Directors.test.js
>    const h1 = screen.queryByText(/Directors Page/g);
```suggestion
  const h1 = screen.queryByText(/Directors Page/);
```

2023-07-28 21:32 UTC, lizbur10 commented on src/__tests__/Home.test.js
>    const h1 = screen.queryByText(/Home Page/g);
```suggestion
  const h1 = screen.queryByText(/Home Page/);
```

2023-07-28 21:32 UTC, lizbur10 commented on src/__tests__/Movie.test.js
> +  const h1 = screen.queryByText(/Doctor Strange/g);
```suggestion
  const h1 = screen.queryByText(/Doctor Strange/);
```

2023-07-28 21:32 UTC, lizbur10 commented on src/__tests__/Movie.test.js
> +  const p = screen.queryByText(/115/g);
```suggestion
  const p = screen.queryByText(/115/);
```

2023-07-28 21:32 UTC, lizbur10 commented on src/__tests__/NavBar.test.js
>    const a = screen.queryByText(/Actors/g);
```suggestion
  const a = screen.queryByText(/Actors/);
```

2023-07-28 21:32 UTC, lizbur10 commented on src/__tests__/index.test.js
> +  expect(screen.getByText(/Home Page/g)).toBeInTheDocument();
```suggestion
  expect(screen.getByText(/Home Page/)).toBeInTheDocument();
```

2023-07-28 21:32 UTC, lizbur10 commented on src/__tests__/index.test.js
> +  expect(screen.getByText(/Actors Page/g)).toBeInTheDocument();
```suggestion
  expect(screen.getByText(/Actors Page/)).toBeInTheDocument();
```

2023-07-28 21:32 UTC, lizbur10 commented on src/__tests__/index.test.js
> +  expect(screen.queryByText(/Directors Page/g)).toBeInTheDocument();
```suggestion
  expect(screen.queryByText(/Directors Page/)).toBeInTheDocument();
```

2023-07-28 21:32 UTC, lizbur10 commented on src/__tests__/index.test.js
> +  expect(screen.queryByText(/Doctor Strange/g)).toBeInTheDocument();
```suggestion
  expect(screen.queryByText(/Doctor Strange/)).toBeInTheDocument();
```

2023-07-28 21:32 UTC, lizbur10 commented on src/__tests__/index.test.js
> +  expect(screen.getByText(/Oops! Looks like something went wrong./g)).toBeInTheDocument()
```suggestion
  expect(screen.getByText(/Oops! Looks like something went wrong./)).toBeInTheDocument()
```

2023-07-31 15:50 UTC, Matt-Eva commented
Thanks for the feedback, Liz! I think those are all good changes.

1. I agree that we should probably just render the titles to our Home Page, along with a link directing a user to view info (I've learned that it's accessibility best practice to not nest links within header tags). I do think it would still make more sense to use MovieCards on Home to render the list of titles, as Card components seem to be traditionally used to render lists of information. Using it on the Movie Page component might be a little redundant, since that page is only rendering info about a single movie anyway. 
2. Good call! I'll add a note about URL encoding.
3. Thanks for flagging. I'll look into that and see if I can replicate the error.
4. I did notice that when I was changing the tests. Thank you for fixing that!

2023-07-31 16:53 UTC, Matt-Eva commented
Ok, I've been coding through the solution, and I've found some problems.

1. Our tests aren't currently checking for MovieCards at all. We pass all of the tests if we just render `Home Page` on the home page route. So we'll need to add some tests for both of these components, I think.
2. Our tests aren't currently checking of either NavBar or our ErrorPage are rendering for every route - they just check if they're being rendered on our Home Route.
3. @lizbur10 R.e. the error you received regarding "/bad-route": Did it look like this?

> `  console.warn
      No routes matched location "/bad-route" `

That's what I see even with all the tests passing.

4. I'm also seeing this console message pop up for our Home test file: 

> `A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --detectOpenHandles to find leaks. Active timers can also cause this, ensure that .unref() was called on them.`

I'm not sure what this is referring to, but can keep digging into it.

2023-08-24 12:41 UTC, lizbur10 requested changes
This is looking really great! A made a few more very minor suggestions (mostly punctuation 🙂 )

2023-08-24 22:34 UTC, Matt-Eva commented on README.md
> +    ├── NavBar.js
```suggestion
    ├── MovieCard.js
```

2023-08-24 22:35 UTC, Matt-Eva commented on README.md
> +    ├── MovieCard.js
```suggestion
    ├── NavBar.js
```

2023-09-27 19:51 UTC, AlveeM commented on README.md
> +- Use `createBrowserRouter` to create a client-side router
Add a `.` after each Learning Goal for accessibility.

2023-09-29 23:14 UTC, Matt-Eva commented on README.md
> +- Use `createBrowserRouter` to create a client-side router
```suggestion
- Use `createBrowserRouter` to create a client-side router.
```

2023-09-29 23:14 UTC, Matt-Eva commented on README.md
> +- Use `RouterProvider` to include the router in your app
```suggestion
- Use `RouterProvider` to include the router in your app.
```

2023-09-29 23:14 UTC, Matt-Eva commented on README.md
>  - Use the `<NavBar>` component to allow client-side navigation
```suggestion
- Use the `<NavBar>` component to allow client-side navigation.
```

2023-09-29 23:14 UTC, Matt-Eva commented on README.md
> +- Use `errorElement` to set up router error handling
```suggestion
- Use `errorElement` to set up router error handling.
```

2023-10-03 12:47 UTC, merged